# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - feature
    - title: 👒 Bugs
      labels:
        - bug
    - title: Other
      labels:
        - '*'
      exclude:
        labels:
          - feature
          - bug
